처음 Entity들 세팅
f-lab-edu/market-early pull request #1
Opened 2024-02-14 14:48 UTC by PreAgile

Entity들 초반 세팅과 기본 Spring data Jpa Repository들을 세팅했습니다.

각 필드값들에 대해 우선 어떤값을 어떻게 쓰일지 몰라서 public으로 열어두고 TestCase들을 작성하고있습니다.

2024-02-17 08:51 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/cart/Cart.java
> +  @OneToOne(fetch = FetchType.LAZY, mappedBy = "cart")
주로 1:1 매핑일때 소유자 (외래키를 가지고있는 테이블) vs 비소유자로나눌때 
소유자 가 JoinColumn을쓰고 비소유자가 mappedBy를써요.  외래키를 갖고있는곳에서만 join을쓰고 아닌곳에서는 안쓰는걸 추천드려요.

2024-02-17 09:15 UTC, kee1993 requested changes
전반적으로 public 인 오브젝트들 다시 리뷰해보고 get/sett 따로 annotate해서 access control할게있는지 보면좋을것같아요. 그외에 코멘트몇개남긴거뺴고는 스타트좋아요,

2024-02-17 09:15 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/cart/CartProduct.java
> +    if(cart == null && product == null) {
이부분은조금 비지니스 로직같은건데, 비지니스로직은 도메인이나 서비스 레이어에서 처리하는게좋고,
엔티티클래스는 기본적인 데이타랑 상태만 하는게좋아요.

2024-02-17 09:15 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/order/OrderProduct.java
> +    if(order == null && product == null) {
비지니스로직 *상단 코멘트와비슷.

2024-02-25 12:13 UTC, PreAgile commented
get/set을 따로 setuserId 이런식으로 메서드로 분리해서 세팅해놓는게 좋을것같다는 말씀이시죠? 그리고 어떤 필드를 어떻게 사용할지 몰라 우선 public으로 열어두긴했습니다.

2024-03-01 06:22 UTC, kee1993 approved these changes
테스트 이제 기본적으로있으니까, 로그인 진행하면서 더추가적인것들하면 될것같아요. 
LGTM!

2024-03-01 06:23 UTC, kee1993 commented
> get/set을 따로 setuserId 이런식으로 메서드로 분리해서 세팅해놓는게 좋을것같다는 말씀이시죠? 그리고 어떤 필드를 어떻게 사용할지 몰라 우선 public으로 열어두긴했습니다.

2024-03-01 06:23 UTC, merged