상품 CRUD API
f-lab-edu/market-early pull request #3
Opened 2024-03-29 01:31 UTC by PreAgile

Product 상품 API 에 대한 CRUD

2024-04-03 07:20 UTC, kee1993 requested changes
전반적으로좋습니다

nit 몇개남겼어요.

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/dto/ProductDto.java
> +
지금 productDTO랑 productReqeustDTO에 
검증 로직 -> Bean Validation같은거 사용해서 넣는거 고려하면좋아요.

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/controller/ProductController.java
> +public class ProductController {
에외처리, 존재하지않는 id, 라든지 input validation 기본적으로할꺼있으면 넣으면될것같아요.

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/controller/ProductController.java
> +    return ResponseEntity.ok(deletedProductId);
204(No Content)를 반환 하는거도 방법이에요.

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/controller/ProductController.java
> +  @GetMapping
pagination 넣어주면좋아요.

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/dto/SubProductDto.java
> +
@NotNull(message = "Name must not be null")
bean validation적극활용하면좋아요

2024-04-03 07:20 UTC, kee1993 commented on src/main/java/kr/flap/domain/model/product/service/ProductService.java
> +    List<Product> products = productRepository.findAll();
pagination 고려

2024-04-03 14:49 UTC, PreAgile commented on src/main/java/kr/flap/domain/model/product/dto/ProductDto.java
> +
✅

2024-04-04 01:32 UTC, PreAgile commented on src/main/java/kr/flap/domain/model/product/controller/ProductController.java
> +    return ResponseEntity.ok(deletedProductId);
✅

2024-04-11 06:15 UTC, PreAgile commented
모두 적용했습니다 확인 부탁드립니다 @kee1993

2024-04-11 23:15 UTC, kee1993 commented
lgtm! 머지하시면될것같습니다 @PreAgile

2024-04-12 07:50 UTC, merged